# Generated by Django 4.1.5 on 2023-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("college", models.CharField(max_length=200)),
                ("mobile_no", models.CharField(max_length=10)),
                ("course_year", models.CharField(max_length=4)),
                ("course_selected", models.CharField(max_length=200)),
            ],
        ),
    ]
